<?php
# DO NOT EDIT THIS FILE.  USE THE ADMIN
if(!defined("FSP")) return;

#general
$cfg['DebugTestonLocalHost']=false;
$cfg['databaselocalhost']='fsp';

#database
$cfg['mysql_server']='localhost';
$cfg['database']='federan8_db179195113';
$cfg['user']='federan8_dbo1791';
$cfg['passwordbase']='cno7o9W80Z';

#administration
if(defined("FSP_ADMIN"))
{
$cfg['admin_user']='admin';
$cfg['admin_pass']='paprika';
}

#units settings
$cfg['WeightUnit']		='1';   //0=Kg 1=lbs
$cfg['DistanceUnit']	='2';   //0=KM 1= Miles 2=NMiles
$cfg['SpeedUnit']		='1';   //0=Km/H 1=Kts
$cfg['AltUnit']			='1';   //0=Meter 1=Feet 
$cfg['LiquidUnit']		='3';   //0=liter 1=gal 2=kg 3=lbs

#Welcome message
$cfg['welcome_message']	='---------------------------------------------------------------------------Welcome to Valkyrie Air---------------------------------------------------------------------------';
?>